version: '3.1'
services:
  app:
    container_name: app
    image: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db