version: '3.5'
services:
  app:
    container_name: app
    image: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db
    networks:
      - backend
      
networks:
  backend:
    name: backend
    driver: bridge