# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# ------------------------ START OF SERVER CONFIGURATION ---------------------------
server:
  port: 8080
  compression:
    enabled: false

# ------------------------- END OF SERVER CONFIGURATION ----------------------------

# ------------------------ START OF SPRING CONFIGURATION ---------------------------
spring:

  main.show-banner: false
  application:
    name: hackovid2020.back
  
  profiles:
    active: development
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/db
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
     data-source-properties:
       cachePrepStmts: true
       prepStmtCacheSize: 250
       prepStmtCacheSqlLimit: 2048
       useServerPrepStmts: true
     read-only: false
      
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate.ddl-auto: none
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      javax.persistence.jdbc.driver: org.mariadb.jdbc.Driver
      javax.persistence.jdbc.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.connection.useUnicode: true
      hibernate.connection.characterEncoding: UTF-8
      hibernate.connection.charSet: UTF-8
      
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false

# ------------------------ END OF SPRING CONFIGURATION -----------------------------

# ------------------------ START OF LIQUIBASE CONFIGURATION ------------------------
#liquibase:
#  default-schema: development
#  url: jdbc:mariadb://localhost:3306/db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true&useSSL=false
#  change-log: classpath:db/db-master-changelog.xml
#  user: root
#  password: root

# ------------------------ END OF LIQUIBASE CONFIGURATION --------------------------
    
  