FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD back.jar /opt/back/
EXPOSE 8080
WORKDIR /opt/back/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "back.jar"]
